### PR TITLE
Adding costs to the schema

### PR DESCRIPTION
**Pull request by thyleung**
Adds all `costs` to schema.

### CODE REVIEW

**Comment by thyleung** [comment]
[Frontend Costs Forms within Services](https://trello.com/c/p87v5nci/455-frontend-costs-forms-within-services)

**Comment by siamalekpour** [comment]
@thyleung I'm taking out `costs` and `reporting_offices` into a private repo. Can you continue development without merging this one in right now?

**Comment by thyleung** [comment]
Sure, there's a few layout changes I can make before this PR is merged in the mean time.  I'll need this PR merged in after that.

**Comment by thyleung** [comment]
Should `suppliers` also be in this repo?  It's not in this PR yet, but could be added too.

**Comment by siamalekpour** [comment]
Suppliers should also go in the private repo. I'll add it in

**Comment by thyleung** [comment]
Closing this PR due to https://github.com/gadventures/gapi-redux/pull/19

**Pull request closed without merging**
