### PR TITLE
Accept dotted string in getRelated

### PR DESCRIPTION
**Pull request by siamalekpour**
Before this change, `getRelated` couldn't access sub-resources nested inside a non-resource object.

An example would be: `accommodation_dossiers.address.city` where `address` is not a resource itself, therefore there was no way to access the `city`.

To access the `city` resource now, you can pass as a string to `getRelated`

```javascript
dispatch(getResource('accommodation_dossiers', 10, {'address.city': null, 'primary_country': null})
```

### CODE REVIEW

**Comment by siamalekpour** [comment]
@oldmill1 Can I bother you with a PR review?

**Comment by jamie-ga** [comment]
Could you possibly add `/build/*` to gitignore and add a build script on deploy?

**Comment by siamalekpour** [comment]
@jamie-ga Since this is an npm package, npm needs the build to be present in the repo.

**Comment by oldmill1** [comment]
looks good 👍 .

**Comment by siamalekpour** [comment]
@jamie-ga @oldmill1 thanks guys

**Pull request merged**
